DROP DATABASE dbProdutos;
CREATE DATABASE dbProdutos;
USE dbProdutos;

CREATE TABLE PRODUTOS ( 
    CODIGO INT, 
    NOME VARCHAR(50), 
    TIPO VARCHAR(25), 
    QUANTIDADE INT, 
    VALOR DECIMAL(10,2) 
);

INSERT INTO PRODUTOS ( CODIGO, NOME, TIPO, QUANTIDADE, VALOR ) 
VALUES ( 1,'IMPRESSORA', 'INFORMATICA', 200, 600.00 );
INSERT INTO PRODUTOS ( CODIGO, NOME, TIPO, QUANTIDADE, VALOR ) 
VALUES ( 2,'CAMERA DIGITAL', 'DIGITAIS', 300, 400.00 );
INSERT INTO PRODUTOS ( CODIGO, NOME, TIPO, QUANTIDADE, VALOR ) 
VALUES ( 3, 'DVD PLAYER', 'ELETRONICOS', 250, 500.00 );
INSERT INTO PRODUTOS ( CODIGO, NOME, TIPO, QUANTIDADE, VALOR ) 
VALUES ( 4,'MONITOR', 'INFORMATICA', 400, 900.00 );
INSERT INTO PRODUTOS ( CODIGO, NOME, TIPO, QUANTIDADE, VALOR ) 
VALUES ( 5,'TELEVISOR', 'ELETRONICOS', 350, 650.00 );
INSERT INTO PRODUTOS ( CODIGO, NOME, TIPO, QUANTIDADE, VALOR ) 
VALUES ( 6,'FILMADORA DIGITAL', 'DIGITAIS', 500, 700.00 );
INSERT INTO PRODUTOS ( CODIGO, NOME, TIPO, QUANTIDADE, VALOR ) 
VALUES ( 7,'CELULAR', 'TELEFONE', 450, 850.00 );
INSERT INTO PRODUTOS ( CODIGO, NOME, TIPO, QUANTIDADE, VALOR ) 
VALUES ( 8,'TECLADO', 'INFORMATICA', 300, 450.00 );
INSERT INTO PRODUTOS ( CODIGO, NOME, TIPO, QUANTIDADE, VALOR ) 
VALUES ( 9,'VIDEOCASSETE', 'ELETRONICOS', 200, 300.00 );
INSERT INTO PRODUTOS ( CODIGO, NOME, TIPO, QUANTIDADE, VALOR ) 
VALUES ( 10,'MOUSE', 'INFORMATICA', 400, 60.00 );

DESC PRODUTOS;
SELECT * FROM PRODUTOS;

-- where com select
SELECT * FROM PRODUTOS WHERE tipo = 'informatica';


SELECT * FROM PRODUTOS WHERE tipo not in ('informatica','eletronicos');

SELECT * FROM PRODUTOS WHERE valor BETWEEN 400.00 AND 700.00;
SELECT * FROM PRODUTOS WHERE valor not BETWEEN 400 AND 600;

SELECT nome FROM PRODUTOS WHERE nome LIKE '%l'
SELECT nome FROM PRODUTOS WHERE nome LIKE '%l%'
SELECT nome FROM PRODUTOS WHERE nome LIKE 'l%'

SELECT * FROM PRODUTOS WHERE nome not LIKE '%M'